### ISSUE TITLE
Chat window lag 

### ISSUE THREAD

**Issue by fionafibration** [TF2HUDsArchive/Broesel-Hud#3]
With hud_saytext_time 0 as my default, opening the chat window causes enough CPU usage for my fans to spin up and audio to become noticeably crackly. I have confirmed this issue occurs on a clean config version of TF2.

**Comment by miyho** [comment]
hypno abandoned us ig

**Comment by Hypnootize** [comment]
I didn't, I checked for this issue and I can't recreate it in any way. The chat is basically as default as it can get and mulitple users told me they never faced any similiar issue while using the HUD, I highly doubt it has anything to to with the HUD.
I have kept this issue open in case someone that sees this, and knows more about it, wants to help.

**Comment by miyho** [comment]
oh, mb
