### ISSUE TITLE
health cross missing texture

### ISSUE THREAD

**Issue by miyho** [TF2HUDsArchive/Broesel-Hud#4]
title says it all

![image](https://github.com/Hypnootize/Broesel-Hud/assets/87745343/3123b313-e048-4c18-b08c-1fd85b9cd581)

**Comment by Hypnootize** [comment]
![hp](https://github.com/Hypnootize/Broesel-Hud/assets/19785551/09ff6d73-636a-4839-b3b7-ce62f61c7248)
Works perfectly fine for me, you are supposed to take both the `resource` and `materials` folders inside the Health Cross customization and paste them in the HUD's root folder.
In the screeshot you are missing the material for the cross bg so make sure you included that when installing the customization
