### ISSUE TITLE
crosshair bug

### ISSUE THREAD

**Issue by NeraWF** [TF2HUDsArchive/Broesel-Hud#5]
ı have custom crosshair but some classes weapon have own crosshair how can ı fix this 
![image](https://github.com/Hypnootize/Broesel-Hud/assets/69982841/97730d78-f1f1-4e6a-b3c9-c84173e655c3)

**Comment by NeraWF** [comment]
and some diffrent classes scout soldier pyro demo and others

**Comment by NeraWF** [comment]
ı closed crosshair in game

**Comment by Hypnootize** [comment]
you can type `crosshair 0` in console to remove the default crosshair

**Comment by NeraWF** [comment]
thank you its gone now
