### ISSUE TITLE
HP Cross

### ISSUE THREAD

**Issue by miyho** [TF2HUDsArchive/Broesel-Hud#7]
Any way to change the hp cross font? ive been trying to do it but nothing till now. I really want it to look like default hud tf2's health cross with a semi-transparent health color inside the health bar, but bigger.
All i could do is this.
![image](https://github.com/Hypnootize/Broesel-Hud/assets/87745343/a80d8c85-3523-4edd-9d93-9b26e72c8bbe)

**Comment by miyho** [comment]
Another options is to make the hp cross asid from the health numbers, wich i think would be better, but i dont have any idea of how to do it.

**Comment by Hypnootize** [comment]
You want the hp to use the default font? if so you can switch the font of ["PlayerStatusHealthValue"](https://github.com/Hypnootize/Broesel-Hud/blob/master/customizations/Health%20Cross/resource/ui/HudPlayerHealth.res#L201) back to the default one which is `"HudClassHealth"` or if you want something bigger you could try `"HudFontMediumSmall"` or `"HudFontMediumSecondary"` for example. Also the default fgcolor is "TanDark"

IIRC the `"PlayerStatusHealthValue"` changes color when buffed as well and to prevent that you can simply change the name of it to something like `"PlayerStatusHealthValueEDIT"` make sure you change the "FieldName" as well!
