### ISSUE TITLE
missing + sign from killfeed assists

### ISSUE THREAD

**Issue by miyho** [TF2HUDsArchive/Broesel-Hud#8]
title says it all

**Comment by Hypnootize** [comment]
Seems to be working fine for me
![killfeed](https://github.com/Hypnootize/Broesel-Hud/assets/19785551/debd0bc1-d3b5-4a7e-ac94-b0cf0e64b40c)

**Comment by miyho** [comment]
oh mb, i changed the font for the minusless damage thing x|
