### ISSUE TITLE
net_graphproportionalfont doesnt working

### ISSUE THREAD

**Issue by NeraWF** [TF2HUDsArchive/Broesel-Hud#9]
net_graphproportionalfont  doesnt working in broesel-hud ı tried other huds and working
i need to change something to work again?

**Comment by Hypnootize** [comment]
Try deleting `Resource/SourceScheme.res`

**Comment by NeraWF** [comment]
no its not working

**Comment by Hypnootize** [comment]
It works for me without `SourceScheme.res`

`net_graphproportionalfont "0"`

![prop 0](https://github.com/Hypnootize/Broesel-Hud/assets/19785551/c658f9b0-513d-4ebf-a735-8d2fdfd29d38)

`net_graphproportionalfont "1"`

![prop 1](https://github.com/Hypnootize/Broesel-Hud/assets/19785551/394ebc1e-8f70-4f83-b814-b9a49e24eeb9)

**Comment by NeraWF** [comment]
its not worked after deleted SourceScheme.res but ı restart game next day and it start working  i dont know why but thanks

**Comment by Hypnootize** [comment]
Yes, all scheme changes require a game restart
